import os
from itertools import product

# Parameters to sweep
CTA_Q = 128
CTA_K = 64
WARP_Q = 32
WARP_K = 64
head_dims = [64, 128]
qk_quant_grans = [2, 3]
dtype_pvaccum = "float"
use_inst_buffer = True
dtypes_out = ["half", "nv_bfloat16"]
is_causals = [True, False]
return_lses = [True, False]
fuse_v_scales = [True, False]
fuse_v_means = [False]

# Output directory
output_dir = os.path.dirname(os.path.abspath(__file__))

script_name = os.path.basename(__file__)
header = f'// this file is automatically generated by running `python {script_name}`\n#include "../qk_int_sv_f8_cuda_sm89.cuh"\n'

def bool_to_int(b):
    return "1" if b else "0"

# Function parameter list
param_list = (
    "  int8_t* Q, int8_t* K, __nv_fp8_e4m3* V, {dtype_out}* O, float* Lse,\n"
    "  float* Q_scale, float* K_scale, float* V_scale, float* V_mean,\n"
    "  const uint32_t batch_size, const uint32_t qo_len, const uint32_t kv_len, const uint32_t num_qo_heads, const uint32_t num_kv_heads,\n"
    "  const uint32_t stride_bz_q, const uint32_t stride_seq_q, const uint32_t stride_h_q,\n"
    "  const uint32_t stride_bz_k, const uint32_t stride_seq_k, const uint32_t stride_h_k,\n"
    "  const uint32_t stride_bz_v, const uint32_t stride_h_v, const uint32_t stride_d_v,\n"
    "  const uint32_t stride_bz_o, const uint32_t stride_seq_o, const uint32_t stride_h_o,\n"
    "  float sm_scale\n"
)

# Generate all combinations
for hd, qkg, dtype_out, causal, lse, fuse_scale, fuse_mean in product(
        head_dims, qk_quant_grans, dtypes_out, is_causals, return_lses, fuse_v_scales, fuse_v_means):
    if fuse_mean and not fuse_scale:
        continue
    filename = (
        f"inst_sm89_ctaq{CTA_Q}_ctak{CTA_K}_warpq{WARP_Q}_warpk{WARP_K}"
        f"_hd{hd}_qkg{qkg}_pvacc{dtype_pvaccum}_ibuf{bool_to_int(use_inst_buffer)}"
        f"_o{dtype_out}_causal{bool_to_int(causal)}_lse{bool_to_int(lse)}"
        f"_fv{bool_to_int(fuse_scale)}_fvm{bool_to_int(fuse_mean)}.cu"
    )
    filepath = os.path.join(output_dir, filename)

    instantiation = (
        f"template void SageAttentionSM89Dispatched<"
        f"{CTA_Q}, {CTA_K}, {WARP_Q}, {WARP_K}, {hd}, {qkg}, {dtype_pvaccum}, "
        f"{str(use_inst_buffer).lower()}, {dtype_out}, "
        f"{str(causal).lower()}, {str(lse).lower()}, "
        f"{str(fuse_scale).lower()}, {str(fuse_mean).lower()}"
        f">(\n{param_list.format(dtype_out=dtype_out)});"
    )

    with open(filepath, "w") as f:
        f.write(header)
        f.write(instantiation + "\n")

print(f"Generated {len(os.listdir(output_dir))} instantiations in '{output_dir}'")
